name: Github Token

on:
  push:
    branches:
      - main

jobs:
  ejemplo:
    runs-on: ubuntu-latest

    steps:
      - name: Astro Deploy
        uses: withastro/action@v0.3.2
        with:
          env: ${{ secrets.GITHUB_TOKEN }}

